version: '3.8'
services:
  database:
    env_file:
      - .env
    container_name: database
    image: postgres:latest
    volumes:
      - ./data/database:/data
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ft_transcendance
    restart: on-failure
  frontend:
    container_name: frontend
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./data/frontend:/app
    networks:
      - ft_transcendance
    restart: on-failure
  backend:
    container_name: backend
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./data/backend:/app
    networks:
      - ft_transcendance
    restart: on-failure

networks:
  ft_transcendance:
    driver: bridge