version: "3.3"
services:
  database:
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/db
    container_name: database
    user: postgres
    build:
      context: docker/database
    image: postgres:latest
    networks:
      - ft_transcendence
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: on-failure
  frontend:
    env_file:
      - .env
    container_name: frontend
    image: frontend
    build:
      args:
        - IP=${IP}
      context: ./docker/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    volumes:
      - ./data/frontend:/app
    networks:
      - ft_transcendence
    restart: on-failure
  backend:
    container_name: backend
    image: backend
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:${PORT}"
    volumes:
      - ./data/backend:/app
      - ./data/avatars:/avatars
    networks:
      - ft_transcendence
    restart: on-failure
networks:
  ft_transcendence:
    driver: bridge
volumes:
  db_data:
