version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data/frontend:/app:cached
  backend:
    container_name: backend
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data/backend:/app:cached