version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: ./docker/frontend/
      dockerfile: Dockerfile
    image: react
    ports:
      - "3000:3000"
    volumes:
      - ./docker/frontend:/app
  backend:
    container_name: backend
    build:
      context: ./docker/backend/
      dockerfile: Dockerfile
    image: server
    ports:
      - "5000:5000"
    volumes:
      - ./docker/frontend:/app